anno:
  annotation:
    COMMON:
      - name: ShdEquip
      - name: bowReset
      - name: CastOKStart
      - name: preHitFrame
      - name: weaponSwing
      - name: weaponLeftSwing
      - name: HitFrame
      - name: 2_HitFrame
      - name: SoundPlay
      - name: PIE
    MCO:
      - name: MCO_WinOpen
        description: 打开轻攻击区间
      - name: MCO_WinClose
        description: 关闭轻攻击区间
      - name: MCO_PowerWinOpen
        description: 打开重攻击区间
      - name: MCO_PowerWinClose
        description: 关闭重攻击区间
      - name: MCO_Recovery
        description: 恢复自由移动
      - name: MCO_ChargedAttack
        description: 进入蓄力攻击
      - name: MCO_TransitionOpen
      - name: MCO_TransitionClose
      - name: PIE
        description: 注解头（来自于payload框架，载体，无特殊意义）
    PRECISION:
      - name: Collision_AttackStart
      - name: Collision_Add
      - name: Collision_Remove
      - name: Collision_ClearTargets
      - name: Collision_Cancel
      - name: Collision_AttackEnd
    AMR:
      - name: animmotion
      - name: animrotation
    SCAR:
      - name: SCAR_ComboStart
      - name: SCAR_ActionData

  payload:
    COMMON:
      - name: "@SGVB"
      - name: "@SGVF"
      - name: "@SGVI"
      - name: "@CAST"
      - name: "@CASTSPELL"
      - name: "@APPLYSPELL"
      - name: "@UNAPPLYSPELL"
      - name: "@SETGHOST"
      - name: "@PLAYPARTICLE"
      - name: "@CAMSHAKE"
    MCO:
      - name: "@SVGF|MCO_AttackSpeed|"
      - name: "@SGVI|MCO_nextattack|"
      - name: "@SGVI|MCO_nextpowerattack|"
    PRECISION:
      - name: "Node()"
      - name: "ID()"
      - name: "NoRecoil"
      - name: "NoTrail"
      - name: "TrailUseTrueLength"
      - name: "WeaponTip"
      - name: "DamageMult()"
      - name: "Length()"
      - name: "LengthMult()"
      - name: "Radius()"
      - name: "RadiusMult()"
      - name: "Duration()"
      - name: "Rotation()"
      - name: "Translation()"
      - name: "Scale()"
    CUSTOM: